# name: Terraform Delete Pipeline

# on: 
#   workflow_dispatch:
    
# env:
#   AWS_REGION: us-east-1
#   TERRAFORM_VERSION: 1.9
  

# jobs:
#   build-ecs-infrastructure:
#     name: Build and Deploy ECS Infrastructure
#     runs-on: ubuntu-latest 
#     defaults:
#       run:
#         working-directory: .
#     steps: 
#       - name: Checkout Repository 
#         uses: actions/checkout@v3

#       - name: Set up Terraform 
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: ${{ env.TERRAFORM_VERSION }}

#       - name: Initialize Terraform 
#         run: |
#           terraform init 
#       - name: Terraform Validate (quick sanity check)
#         run: terraform validate
        
#       - name: Terraform Plan
#         run: terraform plan -out=tfplan
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#           AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

#       - name: Validate Terraform Configuration 
#         if: github.event_name == 'workflow_dispatch'
#         run: terraform destroy -auto-approve 
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#           AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
#           working-directory:  ${{ env.infra_dir }}


### -----------------------------------------LATEST STEPS ------------------------------

name: Terraform Destroy Pipeline

on: 
  workflow_dispatch:
    inputs:
      confirm-destroy:
        description: 'Type YES to confirm destroy (case-sensitive)'
        required: true
        default: 'NO'

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.9.x
  TF_WORKING_DIR: .

jobs:
  terraform-destroy:
    name: Terraform Destroy Resources
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Debug - Show files $ location
        run: |
          pwd 
          ls -la 
          echo "Looking for .tf files in current directory:"
          find . -type f -name "*.tf" || echo "No .tf files found"

      - name: Terraform Init 
        run: terraform init -input=false
        working-directory: ${{ env.TF_WORKING_DIR}}

      - name: Terraform Validate 
        run: terraform validate 

      - name: Terraform Destroy 
        run: terraform plan -destroy -out=destroy.plan -input=false 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

      - name: Show Destroy Plan 
        run: terraform show destroy.plan
          
      - name: Terraform Destroy  confirmation Check 
        if: inputs.confirm_destroy != 'YES'
        run: | 
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "   DESTROY CANCELLED"
          echo "   You did NOT type YES → nothing deleted"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          exit 0

      - name: Terraform Destroy execute 
        if: inputs.confirm_destroy == 'YES' 
        run: terraform apply -destroy -auto-approve destroy.plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}